version: '3.9'
services:
  issuer-node:
    container_name: issuer-node
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - issuer
      - server

  issuer-mongo:
    container_name: issuer-mongo
    image: mongo:5.0.22
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - issuer

volumes:
  mongo-data:
    driver: local

networks:
  issuer:
    driver: bridge
  server:
    driver: bridge
