name: Dockerize and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          dir: "src/config"
          json: ${{ secrets.CONFIG_JSON }}

      - name: Build, tag, and push issuer node image to Amazon ECR
        id: build-issuer-node-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ISSUER_NODE_REPOSITORY: ${{ secrets.ISSUER_NODE_REPOSITORY }}
          ISSUER_NODE_IMAGE_TAG: ${{ secrets.ISSUER_NODE_IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ISSUER_NODE_REPOSITORY:$ISSUER_NODE_IMAGE_TAG . -f ./build/Dockerfile
          docker push $ECR_REGISTRY/$ISSUER_NODE_REPOSITORY:$ISSUER_NODE_IMAGE_TAG